export const adminSections = [
    { path: '/dashboard', key: 'dashboard', label: 'Tổng quan' },
    { path: '/users', key: 'users', label: 'Quản lý người dùng' },
    { path: '/shops', key: 'shops', label: 'Quản lý shop / seller' },
    { path: '/products', key: 'products', label: 'Quản lý sản phẩm' },
    { path: '/categories', key: 'categories', label: 'Quản lý danh mục' },
    { path: '/orders', key: 'orders', label: 'Quản lý đơn hàng' },
    { path: '/payments', key: 'payments', label: 'Thanh toán / doanh thu' },
    { path: '/promotions', key: 'promotions', label: 'Khuyến mãi / voucher' },
    { path: '/reviews', key: 'reviews', label: 'Đánh giá / bình luận' },
    { path: '/reports', key: 'reports', label: 'Báo cáo / khiếu nại' },
    { path: '/banners', key: 'banners', label: 'Banner / giao diện trang chủ' },
    { path: '/notifications', key: 'notifications', label: 'Quản lý thông báo' },
    { path: '/shipping', key: 'shipping', label: 'Quản lý vận chuyển' },
    { path: '/settings', key: 'settings', label: 'Cài đặt hệ thống' },
    { path: '/roles', key: 'roles', label: 'Phân quyền admin' },
]

export const pageData = {
    dashboard: {
        title: 'Trang tổng quan hệ thống',
        description: 'Theo dõi nhanh số liệu toàn sàn, hiệu suất vận hành và các cảnh báo mới nhất.',
        cards: [
            { label: 'Tổng số user', value: '25,480' },
            { label: 'Tổng số seller', value: '1,280' },
            { label: 'Tổng số customer', value: '24,200' },
            { label: 'Tổng số sản phẩm', value: '58,920' },
            { label: 'Tổng số đơn hàng', value: '12,640' },
            { label: 'Doanh thu', value: '2.48 tỷ' },
            { label: 'Đơn chờ xử lý', value: '182' },
            { label: 'Khiếu nại / báo cáo mới', value: '37' },
        ],
        stats: [
            { name: 'Doanh thu hôm nay', value: '186 triệu' },
            { name: 'Top shop bán chạy', value: 'trendmall.vn' },
            { name: 'Top sản phẩm bán chạy', value: 'Tai nghe Bluetooth A12' },
            { name: 'Biểu đồ', value: 'Demo theo ngày / tháng' },
        ],
        tableTitle: 'Doanh thu mô phỏng 7 ngày gần nhất',
        columns: ['Ngày', 'Doanh thu', 'Đơn hàng', 'Tăng trưởng'],
        rows: [
            ['15/04', '210 triệu', '1,420', '+8%'],
            ['16/04', '225 triệu', '1,510', '+7%'],
            ['17/04', '238 triệu', '1,620', '+5%'],
            ['18/04', '242 triệu', '1,700', '+3%'],
            ['19/04', '260 triệu', '1,830', '+7%'],
            ['20/04', '275 triệu', '1,910', '+6%'],
            ['21/04', '286 triệu', '2,020', '+4%'],
        ],
        actions: ['Làm mới số liệu', 'Xem chi tiết dashboard'],
    },

    users: {
        title: 'Quản lý người dùng',
        description: 'Danh sách tất cả tài khoản, phân loại khách hàng, người bán và admin.',
        cards: [
            { label: 'Tất cả tài khoản', value: '25,480' },
            { label: 'Khách hàng', value: '24,200' },
            { label: 'Người bán', value: '1,280' },
            { label: 'Admin', value: '18' },
        ],
        tableTitle: 'Danh sách tài khoản mẫu',
        columns: ['Tên', 'Email', 'Số điện thoại', 'Vai trò', 'Trạng thái'],
        rows: [
            ['Nguyễn Văn A', 'a@gmail.com', '0901234567', 'Customer', 'Hoạt động'],
            ['Trần Thị B', 'b@gmail.com', '0912345678', 'Seller', 'Chờ duyệt'],
            ['Lê Văn C', 'c@gmail.com', '0923456789', 'Admin', 'Hoạt động'],
            ['Phạm Thị D', 'd@gmail.com', '0934567890', 'Customer', 'Bị khóa'],
        ],
        actions: ['Xem chi tiết user', 'Khóa tài khoản', 'Mở khóa tài khoản'],
    },

    shops: {
        title: 'Quản lý shop / seller',
        description: 'Duyệt đăng ký bán hàng, xem doanh thu shop, khóa hoặc mở lại shop.',
        cards: [
            { label: 'Tổng số shop', value: '1,280' },
            { label: 'Shop chờ duyệt', value: '56' },
            { label: 'Shop hoạt động', value: '1,130' },
            { label: 'Shop vi phạm', value: '94' },
        ],
        tableTitle: 'Danh sách shop mẫu',
        columns: ['Tên shop', 'Chủ shop', 'Số sản phẩm', 'Doanh thu', 'Trạng thái'],
        rows: [
            ['trendmall.vn', 'Nguyễn Minh', '128', '420 triệu', 'Hoạt động'],
            ['fashionhouse', 'Lê Lan', '86', '210 triệu', 'Tạm khóa'],
            ['giadung247', 'Trần Nam', '54', '122 triệu', 'Hoạt động'],
            ['techzone', 'Phạm Hưng', '215', '530 triệu', 'Vi phạm'],
        ],
        actions: ['Duyệt đăng ký bán hàng', 'Khóa shop', 'Mở shop'],
    },

    products: {
        title: 'Quản lý sản phẩm',
        description: 'Kiểm duyệt sản phẩm mới, ẩn sản phẩm vi phạm, xem tồn kho và theo shop.',
        cards: [
            { label: 'Tổng sản phẩm', value: '58,920' },
            { label: 'Sản phẩm chờ duyệt', value: '314' },
            { label: 'Đang bán', value: '53,110' },
            { label: 'Bị ẩn', value: '448' },
        ],
        tableTitle: 'Danh sách sản phẩm mẫu',
        columns: ['Tên sản phẩm', 'Shop', 'Danh mục', 'Tồn kho', 'Trạng thái'],
        rows: [
            ['Áo thun basic', 'fashionhouse', 'Thời trang', '120', 'Đang bán'],
            ['Nồi chiên mini', 'giadung247', 'Nhà cửa', '42', 'Đang bán'],
            ['Serum dưỡng da', 'beautycorner', 'Sức khỏe', '0', 'Hết hàng'],
            ['iPhone 14 cũ', 'techzone', 'Điện thoại', '8', 'Bị ẩn'],
        ],
        actions: ['Duyệt sản phẩm', 'Ẩn sản phẩm', 'Xóa sản phẩm'],
    },

    categories: {
        title: 'Quản lý danh mục',
        description: 'Quản lý danh mục cha / con, sắp xếp thứ tự hiển thị và bật tắt danh mục.',
        cards: [
            { label: 'Tổng danh mục', value: '42' },
            { label: 'Danh mục cha', value: '12' },
            { label: 'Danh mục con', value: '30' },
            { label: 'Đang hiển thị', value: '38' },
        ],
        tableTitle: 'Danh mục mẫu',
        columns: ['Tên danh mục', 'Loại', 'Danh mục cha', 'Thứ tự', 'Trạng thái'],
        rows: [
            ['Thời trang', 'Cha', '-', '1', 'Bật'],
            ['Điện thoại', 'Cha', '-', '2', 'Bật'],
            ['Mẹ & bé', 'Cha', '-', '3', 'Bật'],
            ['Ốp lưng', 'Con', 'Điện thoại', '1', 'Bật'],
        ],
        actions: ['Thêm danh mục', 'Sửa danh mục', 'Xóa danh mục'],
    },

    orders: {
        title: 'Quản lý đơn hàng',
        description: 'Theo dõi toàn bộ đơn hàng và xử lý tranh chấp theo từng trạng thái.',
        cards: [
            { label: 'Tổng đơn hàng', value: '12,640' },
            { label: 'Chờ xác nhận', value: '248' },
            { label: 'Đang giao', value: '1,032' },
            { label: 'Hoàn trả / tranh chấp', value: '64' },
        ],
        tableTitle: 'Danh sách đơn hàng mẫu',
        columns: ['Mã đơn', 'Khách hàng', 'Shop', 'Tổng tiền', 'Trạng thái'],
        rows: [
            ['DH1001', 'Nguyễn A', 'trendmall.vn', '350,000đ', 'Chờ xác nhận'],
            ['DH1002', 'Trần B', 'fashionhouse', '120,000đ', 'Đang giao'],
            ['DH1003', 'Lê C', 'techzone', '2,500,000đ', 'Đã giao'],
            ['DH1004', 'Phạm D', 'giadung247', '420,000đ', 'Hoàn trả'],
        ],
        actions: ['Xem chi tiết đơn', 'Xử lý tranh chấp', 'Tìm theo mã đơn'],
    },

    payments: {
        title: 'Quản lý thanh toán / doanh thu',
        description: 'Theo dõi doanh thu sàn, phí hoa hồng, lịch sử thanh toán và yêu cầu rút tiền.',
        cards: [
            { label: 'Tổng doanh thu sàn', value: '2.48 tỷ' },
            { label: 'Phí hoa hồng', value: '182 triệu' },
            { label: 'Yêu cầu rút tiền', value: '29' },
            { label: 'Hoàn tiền cần xử lý', value: '14' },
        ],
        tableTitle: 'Lịch sử thanh toán mẫu',
        columns: ['Mã giao dịch', 'Shop', 'Số tiền', 'Loại', 'Trạng thái'],
        rows: [
            ['GD1001', 'trendmall.vn', '25,000,000đ', 'Rút tiền', 'Chờ duyệt'],
            ['GD1002', 'fashionhouse', '8,400,000đ', 'Hoa hồng', 'Hoàn tất'],
            ['GD1003', 'techzone', '1,200,000đ', 'Hoàn tiền', 'Đang xử lý'],
            ['GD1004', 'giadung247', '12,500,000đ', 'Rút tiền', 'Hoàn tất'],
        ],
        actions: ['Duyệt rút tiền', 'Xử lý hoàn tiền', 'Xem doanh thu shop'],
    },

    promotions: {
        title: 'Quản lý khuyến mãi / voucher',
        description: 'Quản lý voucher toàn sàn, flash sale, freeship và banner khuyến mãi.',
        cards: [
            { label: 'Voucher đang chạy', value: '18' },
            { label: 'Flash sale', value: '6' },
            { label: 'Banner khuyến mãi', value: '12' },
            { label: 'Chương trình freeship', value: '4' },
        ],
        tableTitle: 'Chương trình khuyến mãi mẫu',
        columns: ['Tên chương trình', 'Loại', 'Bắt đầu', 'Kết thúc', 'Trạng thái'],
        rows: [
            ['SALE 4.4', 'Voucher toàn sàn', '01/04', '04/04', 'Đã kết thúc'],
            ['Flash Sale Tech', 'Flash sale', '21/04', '21/04', 'Đang chạy'],
            ['Freeship Extra', 'Freeship', '15/04', '30/04', 'Đang chạy'],
            ['Mã giảm 50K', 'Mã giảm giá', '18/04', '25/04', 'Đang chạy'],
        ],
        actions: ['Tạo voucher', 'Bật / tắt chương trình', 'Quản lý flash sale'],
    },

    reviews: {
        title: 'Quản lý đánh giá / bình luận',
        description: 'Ẩn spam, xóa đánh giá vi phạm và xem phản hồi buyer - seller.',
        cards: [
            { label: 'Tổng đánh giá mới', value: '1,284' },
            { label: 'Bị báo cáo', value: '36' },
            { label: 'Spam nghi ngờ', value: '18' },
            { label: 'Đã xử lý', value: '24' },
        ],
        tableTitle: 'Đánh giá mẫu',
        columns: ['Sản phẩm', 'Người đánh giá', 'Nội dung', 'Mức sao', 'Trạng thái'],
        rows: [
            ['Áo thun basic', 'Nguyễn A', 'Hàng đẹp', '5', 'Hiển thị'],
            ['Nồi chiên mini', 'Trần B', 'Giao chậm', '3', 'Hiển thị'],
            ['Tai nghe A12', 'Lê C', 'Spam link ngoài', '1', 'Bị báo cáo'],
            ['Serum dưỡng da', 'Phạm D', 'Sai mô tả', '2', 'Cần kiểm tra'],
        ],
        actions: ['Ẩn bình luận', 'Xóa đánh giá vi phạm', 'Xem phản hồi buyer - seller'],
    },

    reports: {
        title: 'Quản lý báo cáo / khiếu nại',
        description: 'Xử lý báo cáo shop vi phạm, sản phẩm giả, hoàn tiền và ghi chú quyết định.',
        cards: [
            { label: 'Báo cáo mới', value: '37' },
            { label: 'Khiếu nại đơn hàng', value: '21' },
            { label: 'Yêu cầu hoàn tiền', value: '12' },
            { label: 'Đang xử lý', value: '19' },
        ],
        tableTitle: 'Danh sách báo cáo mẫu',
        columns: ['Loại', 'Đối tượng', 'Người gửi', 'Mô tả', 'Trạng thái'],
        rows: [
            ['Báo cáo shop', 'techzone', 'Nguyễn A', 'Bán hàng sai mô tả', 'Mới'],
            ['Khiếu nại đơn', 'DH1004', 'Trần B', 'Chưa nhận được hàng', 'Đang xử lý'],
            ['Hoàn tiền', 'DH1010', 'Lê C', 'Sản phẩm lỗi', 'Chờ duyệt'],
            ['Báo cáo sản phẩm', 'iPhone 14 cũ', 'Phạm D', 'Nghi hàng giả', 'Mới'],
        ],
        actions: ['Xử lý khiếu nại', 'Ghi chú quyết định', 'Đánh dấu hoàn tất'],
    },

    banners: {
        title: 'Quản lý banner / giao diện trang chủ',
        description: 'Quản lý banner chính, ảnh quảng cáo, danh mục nổi bật và sản phẩm nổi bật.',
        cards: [
            { label: 'Banner chính', value: '5' },
            { label: 'Banner phụ', value: '12' },
            { label: 'Danh mục nổi bật', value: '8' },
            { label: 'Sản phẩm nổi bật', value: '20' },
        ],
        tableTitle: 'Danh sách banner mẫu',
        columns: ['Tên banner', 'Vị trí', 'Ngày bắt đầu', 'Ngày kết thúc', 'Trạng thái'],
        rows: [
            ['Banner Sale 4.4', 'Trang chủ', '01/04', '04/04', 'Đã tắt'],
            ['Banner Flash Sale', 'Trang chủ', '21/04', '21/04', 'Đang bật'],
            ['Banner Freeship', 'Danh mục', '10/04', '30/04', 'Đang bật'],
            ['Banner Tech Week', 'Trang chủ', '22/04', '28/04', 'Chờ bật'],
        ],
        actions: ['Thêm banner', 'Sửa banner', 'Bật / tắt banner'],
    },

    notifications: {
        title: 'Quản lý thông báo',
        description: 'Gửi thông báo hệ thống, đơn hàng, khuyến mãi và vi phạm theo nhóm người dùng.',
        cards: [
            { label: 'Thông báo hôm nay', value: '48' },
            { label: 'Thông báo hệ thống', value: '12' },
            { label: 'Thông báo khuyến mãi', value: '20' },
            { label: 'Thông báo vi phạm', value: '16' },
        ],
        tableTitle: 'Thông báo mẫu',
        columns: ['Tiêu đề', 'Nhóm nhận', 'Loại', 'Thời gian', 'Trạng thái'],
        rows: [
            ['Hệ thống bảo trì', 'Toàn hệ thống', 'Hệ thống', '21/04 08:00', 'Đã gửi'],
            ['Flash sale 12h', 'Customer', 'Khuyến mãi', '21/04 10:00', 'Đã gửi'],
            ['Cảnh báo vi phạm', 'Seller', 'Vi phạm', '21/04 11:00', 'Đã gửi'],
            ['Thông báo đơn hàng', 'Customer', 'Đơn hàng', '21/04 12:00', 'Chờ gửi'],
        ],
        actions: ['Tạo thông báo', 'Gửi theo nhóm', 'Tắt thông báo'],
    },

    shipping: {
        title: 'Quản lý vận chuyển',
        description: 'Theo dõi đơn vị vận chuyển, phí ship, vùng giao hàng và đơn giao thất bại.',
        cards: [
            { label: 'Đơn vị vận chuyển', value: '7' },
            { label: 'Đơn đang giao', value: '1,032' },
            { label: 'Giao thất bại', value: '43' },
            { label: 'Khu vực giao hàng', value: '63 tỉnh/thành' },
        ],
        tableTitle: 'Tình trạng vận chuyển mẫu',
        columns: ['Đơn vị', 'Phí ship', 'Khu vực', 'Đơn lỗi', 'Trạng thái'],
        rows: [
            ['GHN', '25,000đ', 'Toàn quốc', '12', 'Hoạt động'],
            ['GHTK', '23,000đ', 'Toàn quốc', '9', 'Hoạt động'],
            ['J&T', '24,000đ', 'Toàn quốc', '7', 'Hoạt động'],
            ['Shopee Xpress', '20,000đ', 'Toàn quốc', '15', 'Cần theo dõi'],
        ],
        actions: ['Xem đơn giao thất bại', 'Quản lý phí ship', 'Cập nhật khu vực giao'],
    },

    settings: {
        title: 'Quản lý cài đặt hệ thống',
        description: 'Cấu hình website, logo, phí sàn, đăng ký seller và nhật ký hoạt động admin.',
        cards: [
            { label: 'Tên hệ thống', value: 'Shopee Clone Admin' },
            { label: 'Phí sàn', value: '5%' },
            { label: 'Admin đang hoạt động', value: '8' },
            { label: 'Nhật ký hôm nay', value: '126' },
        ],
        tableTitle: 'Cấu hình hệ thống mẫu',
        columns: ['Mục cấu hình', 'Giá trị hiện tại', 'Người cập nhật', 'Thời gian', 'Trạng thái'],
        rows: [
            ['Tên website', 'Shopee Clone', 'Super Admin', '20/04 09:00', 'Đang dùng'],
            ['Phí sàn', '5%', 'Super Admin', '20/04 09:15', 'Đang dùng'],
            ['Đăng ký seller', 'Bật', 'Super Admin', '20/04 09:30', 'Đang dùng'],
            ['Logo hệ thống', 'logo-shopee.png', 'Super Admin', '20/04 10:00', 'Đang dùng'],
        ],
        actions: ['Cập nhật cấu hình', 'Xem nhật ký admin', 'Đổi logo hệ thống'],
    },

    roles: {
        title: 'Phân quyền admin',
        description: 'Quản lý Super Admin và các nhóm admin theo chức năng chuyên trách.',
        cards: [
            { label: 'Super Admin', value: '2' },
            { label: 'Admin user', value: '4' },
            { label: 'Admin sản phẩm', value: '5' },
            { label: 'Admin khiếu nại', value: '3' },
        ],
        tableTitle: 'Danh sách quyền admin mẫu',
        columns: ['Tên quyền', 'Số người', 'Phạm vi', 'Mức quyền', 'Trạng thái'],
        rows: [
            ['Super Admin', '2', 'Toàn hệ thống', 'Cao nhất', 'Hoạt động'],
            ['Admin quản lý user', '4', 'User', 'Trung bình', 'Hoạt động'],
            ['Admin xử lý đơn hàng', '4', 'Order', 'Trung bình', 'Hoạt động'],
            ['Admin xử lý khiếu nại', '3', 'Report', 'Trung bình', 'Hoạt động'],
        ],
        actions: ['Thêm quyền', 'Sửa quyền', 'Gán quyền cho admin'],
    },
}