export const adminSections = [
    { path: '/dashboard', key: 'dashboard', label: 'Tổng quan' },
    { path: '/users', key: 'users', label: 'Quản lý người dùng' },
    { path: '/shops', key: 'shops', label: 'Quản lý shop / seller' },
    { path: '/products', key: 'products', label: 'Quản lý sản phẩm' },
    { path: '/categories', key: 'categories', label: 'Quản lý danh mục' },
    { path: '/orders', key: 'orders', label: 'Quản lý đơn hàng' },
    { path: '/payments', key: 'payments', label: 'Thanh toán / doanh thu' },
    { path: '/promotions', key: 'promotions', label: 'Khuyến mãi / voucher' },
    { path: '/reviews', key: 'reviews', label: 'Đánh giá / bình luận' },
    { path: '/reports', key: 'reports', label: 'Báo cáo / khiếu nại' },
    { path: '/banners', key: 'banners', label: 'Banner / giao diện trang chủ' },
    { path: '/notifications', key: 'notifications', label: 'Quản lý thông báo' },
    { path: '/shipping', key: 'shipping', label: 'Quản lý vận chuyển' },
    { path: '/settings', key: 'settings', label: 'Cài đặt hệ thống' },
    { path: '/roles', key: 'roles', label: 'Phân quyền admin' },
]
