window.ADMIN = {
  NAV: [
    { id: 'dashboard', label: 'Tổng quan', icon: '◆' },
    { id: 'users', label: 'Người dùng', icon: '◍' },
    { id: 'shops', label: 'Shop / Seller', icon: '◉' },
    { id: 'products', label: 'Sản phẩm', icon: '◈' },
    { id: 'orders', label: 'Đơn hàng', icon: '◇' },
    { id: 'payments', label: 'Doanh thu', icon: '◆' },
    { id: 'promotions', label: 'Khuyến mãi', icon: '◎' },
    { id: 'reports', label: 'Khiếu nại', icon: '◐' },
    { id: 'settings', label: 'Cài đặt', icon: '◑' },
  ],
  STATS: [
    { label: 'Tổng người dùng', value: '25,480', tone: 'plain' },
    { label: 'Tổng shop', value: '1,280', tone: 'accent' },
    { label: 'Tổng đơn hôm nay', value: '2,020', tone: 'plain' },
    { label: 'Doanh thu sàn', value: '₫2.48 tỷ', tone: 'dark' },
  ],
  CHART: [210, 225, 238, 242, 260, 275, 286],
  CHART_LABELS: ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'],
  USERS: [
    { name: 'Nguyễn Văn A', email: 'a@gmail.com', phone: '0901234567', role: 'Customer', status: 'Hoạt động', tone: 'ok' },
    { name: 'Trần Thị B', email: 'b@gmail.com', phone: '0912345678', role: 'Seller', status: 'Chờ duyệt', tone: 'warn' },
    { name: 'Lê Văn C', email: 'c@gmail.com', phone: '0923456789', role: 'Admin', status: 'Hoạt động', tone: 'ok' },
    { name: 'Phạm Thị D', email: 'd@gmail.com', phone: '0934567890', role: 'Customer', status: 'Bị khóa', tone: 'bad' },
  ],
  ORDERS: [
    { id: 'DH1001', customer: 'Nguyễn A', shop: 'trendmall.vn', total: '₫350.000', status: 'Chờ xác nhận', tone: 'warn' },
    { id: 'DH1002', customer: 'Trần B', shop: 'fashionhouse', total: '₫120.000', status: 'Đang giao', tone: 'cool' },
    { id: 'DH1003', customer: 'Lê C', shop: 'techzone', total: '₫2.500.000', status: 'Đã giao', tone: 'ok' },
    { id: 'DH1004', customer: 'Phạm D', shop: 'giadung247', total: '₫420.000', status: 'Hoàn trả', tone: 'bad' },
    { id: 'DH1005', customer: 'Vũ E', shop: 'beautycorner', total: '₫890.000', status: 'Đang giao', tone: 'cool' },
  ],
  ACTIVITY: [
    { glyph: 'S', dark: false, title: 'trendmall.vn yêu cầu rút ₫25.000.000', time: '5 phút trước · Tài chính' },
    { glyph: 'R', dark: true, title: '12 báo cáo mới chờ kiểm duyệt', time: '14 phút trước · Khiếu nại' },
    { glyph: 'P', dark: false, title: 'Duyệt 314 sản phẩm mới', time: '1 giờ trước · Sản phẩm' },
    { glyph: 'B', dark: true, title: 'Bật banner Tech Week 22/04', time: '2 giờ trước · Banner' },
  ],
};
